

import type { AthkarCategory, Zikr, Juz, Surah, Reciter, KhatmaGoal } from './types';

export const khatmaGoals: KhatmaGoal[] = [
    { id: '30_days', title: 'شهر واحد', description: 'قراءة يومية: جزء واحد', days: 30, pagesPerDay: 20 },
    { id: '60_days', title: 'شهرين', description: 'قراءة يومية: 10 صفحات', days: 60, pagesPerDay: 10 },
    { id: '120_days', title: 'أربع أشهر', description: 'قراءة يومية: خمس صفحات', days: 120, pagesPerDay: 5 },
    { id: '15_days', title: 'خمسة عشر يوماً', description: 'قراءة يومية: جزئين', days: 15, pagesPerDay: 40 },
    { id: '10_days', title: 'عشرة أيام', description: 'قراءة يومية: 3 أجزاء', days: 10, pagesPerDay: 60 },
    { id: '40_days', title: 'أربعون يوماً', description: 'قراءة يومية: 15 صفحة', days: 40, pagesPerDay: 15 },
    { id: '604_days', title: '604 أيام', description: 'قراءة يومية: صفحة واحدة', days: 604, pagesPerDay: 1 },
];


export const juzs: Juz[] = [
    { id: 1, name: 'الجزء 1', startingPage: 1 },
    { id: 2, name: 'الجزء 2', startingPage: 22 },
    { id: 3, name: 'الجزء 3', startingPage: 42 },
    { id: 4, name: 'الجزء 4', startingPage: 62 },
    { id: 5, name: 'الجزء 5', startingPage: 82 },
    { id: 6, name: 'الجزء 6', startingPage: 102 },
    { id: 7, name: 'الجزء 7', startingPage: 121 },
    { id: 8, name: 'الجزء 8', startingPage: 142 },
    { id: 9, name: 'الجزء 9', startingPage: 162 },
    { id: 10, name: 'الجزء 10', startingPage: 182 },
    { id: 11, name: 'الجزء 11', startingPage: 201 },
    { id: 12, name: 'الجزء 12', startingPage: 222 },
    { id: 13, name: 'الجزء 13', startingPage: 242 },
    { id: 14, name: 'الجزء 14', startingPage: 262 },
    { id: 15, name: 'الجزء 15', startingPage: 282 },
    { id: 16, name: 'الجزء 16', startingPage: 302 },
    { id: 17, name: 'الجزء 17', startingPage: 322 },
    { id: 18, name: 'الجزء 18', startingPage: 342 },
    { id: 19, name: 'الجزء 19', startingPage: 362 },
    { id: 20, name: 'الجزء 20', startingPage: 382 },
    { id: 21, name: 'الجزء 21', startingPage: 402 },
    { id: 22, name: 'الجزء 22', startingPage: 422 },
    { id: 23, name: 'الجزء 23', startingPage: 442 },
    { id: 24, name: 'الجزء 24', startingPage: 462 },
    { id: 25, name: 'الجزء 25', startingPage: 482 },
    { id: 26, name: 'الجزء 26', startingPage: 502 },
    { id: 27, name: 'الجزء 27', startingPage: 522 },
    { id: 28, name: 'الجزء 28', startingPage: 542 },
    { id: 29, name: 'الجزء 29', startingPage: 562 },
    { id: 30, name: 'الجزء 30', startingPage: 582 },
];

export const surahList: Surah[] = [
    { "number": 1, "name": "الفاتحة", "englishName": "Al-Fatiha", "numberOfAyahs": 7, "revelationType": "Meccan", "startingPage": 1 },
    { "number": 2, "name": "البقرة", "englishName": "Al-Baqara", "numberOfAyahs": 286, "revelationType": "Medinan", "startingPage": 2 },
    { "number": 3, "name": "آل عمران", "englishName": "Aal-e-Imran", "numberOfAyahs": 200, "revelationType": "Medinan", "startingPage": 50 },
    { "number": 4, "name": "النساء", "englishName": "An-Nisa", "numberOfAyahs": 176, "revelationType": "Medinan", "startingPage": 77 },
    { "number": 5, "name": "المائدة", "englishName": "Al-Ma'idah", "numberOfAyahs": 120, "revelationType": "Medinan", "startingPage": 106 },
    { "number": 6, "name": "الأنعام", "englishName": "Al-An'am", "numberOfAyahs": 165, "revelationType": "Meccan", "startingPage": 128 },
    { "number": 7, "name": "الأعراف", "englishName": "Al-A'raf", "numberOfAyahs": 206, "revelationType": "Meccan", "startingPage": 151 },
    { "number": 8, "name": "الأنفال", "englishName": "Al-Anfal", "numberOfAyahs": 75, "revelationType": "Medinan", "startingPage": 177 },
    { "number": 9, "name": "التوبة", "englishName": "At-Tawbah", "numberOfAyahs": 129, "revelationType": "Medinan", "startingPage": 187 },
    { "number": 10, "name": "يونس", "englishName": "Yunus", "numberOfAyahs": 109, "revelationType": "Meccan", "startingPage": 208 },
    { "number": 11, "name": "هود", "englishName": "Hud", "numberOfAyahs": 123, "revelationType": "Meccan", "startingPage": 221 },
    { "number": 12, "name": "يوسف", "englishName": "Yusuf", "numberOfAyahs": 111, "revelationType": "Meccan", "startingPage": 235 },
    { "number": 13, "name": "الرعد", "englishName": "Ar-Ra'd", "numberOfAyahs": 43, "revelationType": "Medinan", "startingPage": 249 },
    { "number": 14, "name": "ابراهيم", "englishName": "Ibrahim", "numberOfAyahs": 52, "revelationType": "Meccan", "startingPage": 255 },
    { "number": 15, "name": "الحجر", "englishName": "Al-Hijr", "numberOfAyahs": 99, "revelationType": "Meccan", "startingPage": 262 },
    { "number": 16, "name": "النحل", "englishName": "An-Nahl", "numberOfAyahs": 128, "revelationType": "Meccan", "startingPage": 267 },
    { "number": 17, "name": "الإسراء", "englishName": "Al-Isra", "numberOfAyahs": 111, "revelationType": "Meccan", "startingPage": 282 },
    { "number": 18, "name": "الكهف", "englishName": "Al-Kahf", "numberOfAyahs": 110, "revelationType": "Meccan", "startingPage": 293 },
    { "number": 19, "name": "مريم", "englishName": "Maryam", "numberOfAyahs": 98, "revelationType": "Meccan", "startingPage": 305 },
    { "number": 20, "name": "طه", "englishName": "Taha", "numberOfAyahs": 135, "revelationType": "Meccan", "startingPage": 312 },
    { "number": 21, "name": "الأنبياء", "englishName": "Al-Anbiya", "numberOfAyahs": 112, "revelationType": "Meccan", "startingPage": 322 },
    { "number": 22, "name": "الحج", "englishName": "Al-Hajj", "numberOfAyahs": 78, "revelationType": "Medinan", "startingPage": 332 },
    { "number": 23, "name": "المؤمنون", "englishName": "Al-Mu'minun", "numberOfAyahs": 118, "revelationType": "Meccan", "startingPage": 342 },
    { "number": 24, "name": "النور", "englishName": "An-Nur", "numberOfAyahs": 64, "revelationType": "Medinan", "startingPage": 350 },
    { "number": 25, "name": "الفرقان", "englishName": "Al-Furqan", "numberOfAyahs": 77, "revelationType": "Meccan", "startingPage": 359 },
    { "number": 26, "name": "الشعراء", "englishName": "Ash-Shu'ara", "numberOfAyahs": 227, "revelationType": "Meccan", "startingPage": 367 },
    { "number": 27, "name": "النمل", "englishName": "An-Naml", "numberOfAyahs": 93, "revelationType": "Meccan", "startingPage": 377 },
    { "number": 28, "name": "القصص", "englishName": "Al-Qasas", "numberOfAyahs": 88, "revelationType": "Meccan", "startingPage": 385 },
    { "number": 29, "name": "العنكبوت", "englishName": "Al-Ankabut", "numberOfAyahs": 69, "revelationType": "Meccan", "startingPage": 396 },
    { "number": 30, "name": "الروم", "englishName": "Ar-Rum", "numberOfAyahs": 60, "revelationType": "Meccan", "startingPage": 404 },
    { "number": 31, "name": "لقمان", "englishName": "Luqman", "numberOfAyahs": 34, "revelationType": "Meccan", "startingPage": 411 },
    { "number": 32, "name": "السجدة", "englishName": "As-Sajda", "numberOfAyahs": 30, "revelationType": "Meccan", "startingPage": 415 },
    { "number": 33, "name": "الأحزاب", "englishName": "Al-Ahzab", "numberOfAyahs": 73, "revelationType": "Medinan", "startingPage": 418 },
    { "number": 34, "name": "سبأ", "englishName": "Saba", "numberOfAyahs": 54, "revelationType": "Meccan", "startingPage": 428 },
    { "number": 35, "name": "فاطر", "englishName": "Fatir", "numberOfAyahs": 45, "revelationType": "Meccan", "startingPage": 434 },
    { "number": 36, "name": "يس", "englishName": "Ya-Sin", "numberOfAyahs": 83, "revelationType": "Meccan", "startingPage": 440 },
    { "number": 37, "name": "الصافات", "englishName": "As-Saffat", "numberOfAyahs": 182, "revelationType": "Meccan", "startingPage": 446 },
    { "number": 38, "name": "ص", "englishName": "Sad", "numberOfAyahs": 88, "revelationType": "Meccan", "startingPage": 453 },
    { "number": 39, "name": "الزمر", "englishName": "Az-Zumar", "numberOfAyahs": 75, "revelationType": "Meccan", "startingPage": 458 },
    { "number": 40, "name": "غافر", "englishName": "Ghafir", "numberOfAyahs": 85, "revelationType": "Meccan", "startingPage": 467 },
    { "number": 41, "name": "فصلت", "englishName": "Fussilat", "numberOfAyahs": 54, "revelationType": "Meccan", "startingPage": 477 },
    { "number": 42, "name": "الشورى", "englishName": "Ash-Shuraa", "numberOfAyahs": 53, "revelationType": "Meccan", "startingPage": 483 },
    { "number": 43, "name": "الزخرف", "englishName": "Az-Zukhruf", "numberOfAyahs": 89, "revelationType": "Meccan", "startingPage": 489 },
    { "number": 44, "name": "الدخان", "englishName": "Ad-Dukhan", "numberOfAyahs": 59, "revelationType": "Meccan", "startingPage": 496 },
    { "number": 45, "name": "الجاثية", "englishName": "Al-Jathiya", "numberOfAyahs": 37, "revelationType": "Meccan", "startingPage": 499 },
    { "number": 46, "name": "الأحقاف", "englishName": "Al-Ahqaf", "numberOfAyahs": 35, "revelationType": "Meccan", "startingPage": 502 },
    { "number": 47, "name": "محمد", "englishName": "Muhammad", "numberOfAyahs": 38, "revelationType": "Medinan", "startingPage": 507 },
    { "number": 48, "name": "الفتح", "englishName": "Al-Fath", "numberOfAyahs": 29, "revelationType": "Medinan", "startingPage": 511 },
    { "number": 49, "name": "الحجرات", "englishName": "Al-Hujurat", "numberOfAyahs": 18, "revelationType": "Medinan", "startingPage": 515 },
    { "number": 50, "name": "ق", "englishName": "Qaf", "numberOfAyahs": 45, "revelationType": "Meccan", "startingPage": 518 },
    { "number": 51, "name": "الذاريات", "englishName": "Adh-Dhariyat", "numberOfAyahs": 60, "revelationType": "Meccan", "startingPage": 520 },
    { "number": 52, "name": "الطور", "englishName": "At-Tur", "numberOfAyahs": 49, "revelationType": "Meccan", "startingPage": 523 },
    { "number": 53, "name": "النجم", "englishName": "An-Najm", "numberOfAyahs": 62, "revelationType": "Meccan", "startingPage": 526 },
    { "number": 54, "name": "القمر", "englishName": "Al-Qamar", "numberOfAyahs": 55, "revelationType": "Meccan", "startingPage": 528 },
    { "number": 55, "name": "الرحمن", "englishName": "Ar-Rahman", "numberOfAyahs": 78, "revelationType": "Medinan", "startingPage": 531 },
    { "number": 56, "name": "الواقعة", "englishName": "Al-Waqi'a", "numberOfAyahs": 96, "revelationType": "Meccan", "startingPage": 534 },
    { "number": 57, "name": "الحديد", "englishName": "Al-Hadid", "numberOfAyahs": 29, "revelationType": "Medinan", "startingPage": 537 },
    { "number": 58, "name": "المجادلة", "englishName": "Al-Mujadila", "numberOfAyahs": 22, "revelationType": "Medinan", "startingPage": 542 },
    { "number": 59, "name": "الحشر", "englishName": "Al-Hashr", "numberOfAyahs": 24, "revelationType": "Medinan", "startingPage": 545 },
    { "number": 60, "name": "الممتحنة", "englishName": "Al-Mumtahanah", "numberOfAyahs": 13, "revelationType": "Medinan", "startingPage": 549 },
    { "number": 61, "name": "الصف", "englishName": "As-Saf", "numberOfAyahs": 14, "revelationType": "Medinan", "startingPage": 551 },
    { "number": 62, "name": "الجمعة", "englishName": "Al-Jumu'a", "numberOfAyahs": 11, "revelationType": "Medinan", "startingPage": 553 },
    { "number": 63, "name": "المنافقون", "englishName": "Al-Munafiqun", "numberOfAyahs": 11, "revelationType": "Medinan", "startingPage": 554 },
    { "number": 64, "name": "التغابن", "englishName": "At-Taghabun", "numberOfAyahs": 18, "revelationType": "Medinan", "startingPage": 556 },
    { "number": 65, "name": "الطلاق", "englishName": "At-Talaq", "numberOfAyahs": 12, "revelationType": "Medinan", "startingPage": 558 },
    { "number": 66, "name": "التحريم", "englishName": "At-Tahrim", "numberOfAyahs": 12, "revelationType": "Medinan", "startingPage": 560 },
    { "number": 67, "name": "الملك", "englishName": "Al-Mulk", "numberOfAyahs": 30, "revelationType": "Meccan", "startingPage": 562 },
    { "number": 68, "name": "القلم", "englishName": "Al-Qalam", "numberOfAyahs": 52, "revelationType": "Meccan", "startingPage": 564 },
    { "number": 69, "name": "الحاقة", "englishName": "Al-Haqqah", "numberOfAyahs": 52, "revelationType": "Meccan", "startingPage": 566 },
    { "number": 70, "name": "المعارج", "englishName": "Al-Ma'arij", "numberOfAyahs": 44, "revelationType": "Meccan", "startingPage": 568 },
    { "number": 71, "name": "نوح", "englishName": "Nuh", "numberOfAyahs": 28, "revelationType": "Meccan", "startingPage": 570 },
    { "number": 72, "name": "الجن", "englishName": "Al-Jinn", "numberOfAyahs": 28, "revelationType": "Meccan", "startingPage": 572 },
    { "number": 73, "name": "المزمل", "englishName": "Al-Muzzammil", "numberOfAyahs": 20, "revelationType": "Meccan", "startingPage": 574 },
    { "number": 74, "name": "المدثر", "englishName": "Al-Muddaththir", "numberOfAyahs": 56, "revelationType": "Meccan", "startingPage": 575 },
    { "number": 75, "name": "القيامة", "englishName": "Al-Qiyamah", "numberOfAyahs": 40, "revelationType": "Meccan", "startingPage": 577 },
    { "number": 76, "name": "الانسان", "englishName": "Al-Insan", "numberOfAyahs": 31, "revelationType": "Medinan", "startingPage": 578 },
    { "number": 77, "name": "المرسلات", "englishName": "Al-Mursalat", "numberOfAyahs": 50, "revelationType": "Meccan", "startingPage": 580 },
    { "number": 78, "name": "النبأ", "englishName": "An-Naba", "numberOfAyahs": 40, "revelationType": "Meccan", "startingPage": 582 },
    { "number": 79, "name": "النازعات", "englishName": "An-Nazi'at", "numberOfAyahs": 46, "revelationType": "Meccan", "startingPage": 583 },
    { "number": 80, "name": "عبس", "englishName": "Abasa", "numberOfAyahs": 42, "revelationType": "Meccan", "startingPage": 585 },
    { "number": 81, "name": "التكوير", "englishName": "At-Takwir", "numberOfAyahs": 29, "revelationType": "Meccan", "startingPage": 586 },
    { "number": 82, "name": "الإنفطار", "englishName": "Al-Infitar", "numberOfAyahs": 19, "revelationType": "Meccan", "startingPage": 587 },
    { "number": 83, "name": "المطففين", "englishName": "Al-Mutaffifin", "numberOfAyahs": 36, "revelationType": "Meccan", "startingPage": 587 },
    { "number": 84, "name": "الإنشقاق", "englishName": "Al-Inshiqaq", "numberOfAyahs": 25, "revelationType": "Meccan", "startingPage": 589 },
    { "number": 85, "name": "البروج", "englishName": "Al-Buruj", "numberOfAyahs": 22, "revelationType": "Meccan", "startingPage": 590 },
    { "number": 86, "name": "الطارق", "englishName": "At-Tariq", "numberOfAyahs": 17, "revelationType": "Meccan", "startingPage": 591 },
    { "number": 87, "name": "الأعلى", "englishName": "Al-A'la", "numberOfAyahs": 19, "revelationType": "Meccan", "startingPage": 591 },
    { "number": 88, "name": "الغاشية", "englishName": "Al-Ghashiyah", "numberOfAyahs": 26, "revelationType": "Meccan", "startingPage": 592 },
    { "number": 89, "name": "الفجر", "englishName": "Al-Fajr", "numberOfAyahs": 30, "revelationType": "Meccan", "startingPage": 593 },
    { "number": 90, "name": "البلد", "englishName": "Al-Balad", "numberOfAyahs": 20, "revelationType": "Meccan", "startingPage": 594 },
    { "number": 91, "name": "الشمس", "englishName": "Ash-Shams", "numberOfAyahs": 15, "revelationType": "Meccan", "startingPage": 595 },
    { "number": 92, "name": "الليل", "englishName": "Al-Layl", "numberOfAyahs": 21, "revelationType": "Meccan", "startingPage": 595 },
    { "number": 93, "name": "الضحى", "englishName": "Ad-Duhaa", "numberOfAyahs": 11, "revelationType": "Meccan", "startingPage": 596 },
    { "number": 94, "name": "الشرح", "englishName": "Ash-Sharh", "numberOfAyahs": 8, "revelationType": "Meccan", "startingPage": 596 },
    { "number": 95, "name": "التين", "englishName": "At-Tin", "numberOfAyahs": 8, "revelationType": "Meccan", "startingPage": 597 },
    { "number": 96, "name": "العلق", "englishName": "Al-Alaq", "numberOfAyahs": 19, "revelationType": "Meccan", "startingPage": 597 },
    { "number": 97, "name": "القدر", "englishName": "Al-Qadr", "numberOfAyahs": 5, "revelationType": "Meccan", "startingPage": 598 },
    { "number": 98, "name": "البينة", "englishName": "Al-Bayyinah", "numberOfAyahs": 8, "revelationType": "Medinan", "startingPage": 598 },
    { "number": 99, "name": "الزلزلة", "englishName": "Az-Zalzalah", "numberOfAyahs": 8, "revelationType": "Medinan", "startingPage": 599 },
    { "number": 100, "name": "العاديات", "englishName": "Al-Adiyat", "numberOfAyahs": 11, "revelationType": "Meccan", "startingPage": 599 },
    { "number": 101, "name": "القارعة", "englishName": "Al-Qari'a", "numberOfAyahs": 11, "revelationType": "Meccan", "startingPage": 600 },
    { "number": 102, "name": "التكاثر", "englishName": "At-Takathur", "numberOfAyahs": 8, "revelationType": "Meccan", "startingPage": 600 },
    { "number": 103, "name": "العصر", "englishName": "Al-Asr", "numberOfAyahs": 3, "revelationType": "Meccan", "startingPage": 601 },
    { "number": 104, "name": "الهمزة", "englishName": "Al-Humazah", "numberOfAyahs": 9, "revelationType": "Meccan", "startingPage": 601 },
    { "number": 105, "name": "الفيل", "englishName": "Al-Fil", "numberOfAyahs": 5, "revelationType": "Meccan", "startingPage": 601 },
    { "number": 106, "name": "قريش", "englishName": "Quraysh", "numberOfAyahs": 4, "revelationType": "Meccan", "startingPage": 602 },
    { "number": 107, "name": "الماعون", "englishName": "Al-Ma'un", "numberOfAyahs": 7, "revelationType": "Meccan", "startingPage": 602 },
    { "number": 108, "name": "الكوثر", "englishName": "Al-Kawthar", "numberOfAyahs": 3, "revelationType": "Meccan", "startingPage": 602 },
    { "number": 109, "name": "الكافرون", "englishName": "Al-Kafirun", "numberOfAyahs": 6, "revelationType": "Meccan", "startingPage": 603 },
    { "number": 110, "name": "النصر", "englishName": "An-Nasr", "numberOfAyahs": 3, "revelationType": "Medinan", "startingPage": 603 },
    { "number": 111, "name": "المسد", "englishName": "Al-Masad", "numberOfAyahs": 5, "revelationType": "Meccan", "startingPage": 603 },
    { "number": 112, "name": "الإخلاص", "englishName": "Al-Ikhlas", "numberOfAyahs": 4, "revelationType": "Meccan", "startingPage": 604 },
    { "number": 113, "name": "الفلق", "englishName": "Al-Falaq", "numberOfAyahs": 5, "revelationType": "Meccan", "startingPage": 604 },
    { "number": 114, "name": "الناس", "englishName": "An-Nas", "numberOfAyahs": 6, "revelationType": "Meccan", "startingPage": 604 }
];

export const reciters: Reciter[] = [
    { identifier: 'Alafasy_128kbps', name: 'مشاري العفاسي', englishName: 'Mishary Alafasy' },
    { identifier: 'Abdurrahmaan_As-Sudais_128kbps', name: 'عبدالرحمن السديس', englishName: 'Abdurrahman As-Sudais' },
    { identifier: 'Maher_AlMuaiqly_128kbps', name: 'ماهر المعيقلي', englishName: 'Maher Al Muaqily' },
    { identifier: 'Minshawy_Mujawwad_128kbps', name: 'محمد صديق المنشاوي (مجود)', englishName: 'Minshawi (Mujawwad)' },
    { identifier: 'Husary_Mujawwad_128kbps', name: 'محمود خليل الحصري (مجود)', englishName: 'Mahmud Al Husary (Mujawwad)' },
    { identifier: 'Saad_Al-Ghamdi_128kbps', name: 'سعد الغامدي', englishName: 'Saad Al Ghamidi' },
    { identifier: 'Abdul_Basit_Murattal_128kbps', name: 'عبد الباسط عبد الصمد (مرتل)', englishName: 'Abdul Basit (Murattal)' },
    { identifier: 'Ahmed_Alajamy_128kbps', name: 'أحمد بن علي العجمي', englishName: 'Ahmed Al Ajamy' },
    { identifier: 'Yasser_Ad-Dussary_128kbps', name: 'ياسر الدوسري', englishName: 'Yasser Ad-Dossari' },
    { identifier: 'Nasser_Alqatami_128kbps', name: 'ناصر القطامي', englishName: 'Nasser Al Qatami' },
    { identifier: 'Fares_Abbad_128kbps', name: 'فارس عباد', englishName: 'Fares Abbad' },
    { identifier: 'Saood_Shuraym_128kbps', name: 'سعود الشريم', englishName: 'Saood Shuraym' },
    { identifier: 'Khalifa_Al-Tunaiji_128kbps', name: 'خليفة الطنيجي', englishName: 'Khalifa Al-Tunaiji' },
    { identifier: 'Abu_Bakr_Ash-Shaatree_128kbps', name: 'أبو بكر الشاطري', englishName: 'Abu Bakr Al Shatri' },
    { identifier: 'Abdullah_Basfar_128kbps', name: 'عبدالله بصفر', englishName: 'Abdullah Basfar' },
    { identifier: 'Husary_128kbps', name: 'محمود خليل الحصري (مرتل)', englishName: 'Mahmud Al Husary (Murattal)' },
    { identifier: 'Muhammad_Ayyoub_128kbps', name: 'محمد أيوب', englishName: 'Muhammad Ayyoub' },
    { identifier: 'Muhammad_Jibreel_128kbps', name: 'محمد جبريل', englishName: 'Muhammad Jibreel' },
    { identifier: 'Hudhaify_128kbps', name: 'علي الحذيفي', englishName: 'Ali Al Huthaify' },
    { identifier: 'Hani_Rifai_128kbps', name: 'هاني الرفاعي', englishName: 'Hani Ar-Rifai' },
    { identifier: 'Mahmoud_Ali_Al-Banna_128kbps', name: 'محمود علي البنا', englishName: 'Mahmoud Ali Al-Banna' },
    { identifier: 'Salah_Budair_128kbps', name: 'صلاح البدير', englishName: 'Salah Budair' },
    { identifier: 'Salah_Bukhatir_128kbps', name: 'صلاح بوخاطر', englishName: 'Salah Al-Bukhatir' },
    { identifier: 'Mohamed_El-Tablawi_128kbps', name: 'محمد الطبلاوي', englishName: 'Mohamed Al-Tablawi' },
    { identifier: 'Abdur-Rashid_Sufi_128kbps', name: 'عبد الرشيد صوفي', englishName: 'Abdur-Rashid Sufi' },
];


export const athkarCategories: AthkarCategory[] = [
    { id: 'sabah', title: 'أذكار الصباح' },
    { id: 'masaa', title: 'أذكار المساء' },
    { id: 'postPrayer', title: 'أذكار بعد الصلاة' },
    { id: 'sleep', title: 'أذكار النوم' },
    { id: 'waking', title: 'أذكار الإستيقاظ' },
    { id: 'wudhu', title: 'أذكار الوضوء' },
    { id: 'mosque', title: 'أذكار المسجد' },
    { id: 'food', title: 'أذكار الطعام' },
    { id: 'home', title: 'أذكار المنزل' },
    { id: 'travel', title: 'أذكار السفر' },
    { id: 'toilet', title: 'أذكار الخلاء' },
    { id: 'other', title: 'أذكار متفرقة' },
];

export const athkarData: { [key: string]: Zikr[] } = {
    'sabah': [
        { id: 101, category: 'sabah', text: 'اللهم أنت ربي، لا إله إلا أنت، خلَقتني وأنا عبدك، وأنا على عهدك ووعدك ما استطعت، أعوذ بك من شرِّ ما صنعت، أبُوء لك بنعمتك عليّ وأبوء بذنبي، فاغفر لي؛ فإنه لا يغفر الذنوب إلا أنت.', count: 1, reference: 'رواه البخاري' },
        { id: 102, category: 'sabah', text: 'اللهم بك أصبحنا، وبك أمسينا، وبك نحيا، وبك نموت، وإليك النشور.', count: 1, reference: 'صحيح؛ رواه الترمذي' },
        { id: 103, category: 'sabah', text: 'أصبحنا على فِطرة الإسلام، وكلمة الإخلاص، ودين نبينا محمد -صلى الله عليه وسلم- ومِلة أبينا إبراهيم حنيفًا مسلمًا وما كان من المشركين.', count: 1, reference: 'صحيح؛ رواه أحمد' },
        { id: 104, category: 'sabah', text: 'اللهم إني أسألك العافية في الدنيا والآخرة، اللهم إني أسألك العفو والعافية في ديني ودنياي، وأهلي ومالي، اللهم استُر عوراتي، وآمِن رَوعاتي، اللهم احفظني من بين يدي ومن خلفي، وعن يميني وعن شمالي، ومن فوقي، وأعوذ بعظمتك أن أُغتال من تحتي.', count: 1, reference: 'صحيح؛ رواه أبو داود' },
        { id: 105, category: 'sabah', text: 'اللهم عافني في بدني، اللهم عافني في سمعي، اللهم عافني في بصري، لا إله إلا أنت.', count: 3, reference: 'حسن؛ رواه أحمد' },
        { id: 106, category: 'sabah', text: 'اللهم إني أعوذ بك من الكفر والفقر، اللهم إني أعوذ بك من عذاب القبر، لا إله إلا أنت.', count: 3, reference: 'حسن؛ رواه أحمد' },
        { id: 107, category: 'sabah', text: 'أصبحنا وأصبح المُلك لله، والحمد لله، لا إله إلا الله وحده لا شريك له، له الملك وله الحمد وهو على كل شيء قدير، ربِّ أسألك خير ما في هذا اليوم، وخير ما بعده، وأعوذ بك من شرِّ ما في هذا اليوم، وشر ما بعده، ربِّ أعوذ بك من الكسل، وسوء الكِبَر، ربِّ أعوذ بك من عذابٍ في النار وعذاب في القبر.', count: 1, reference: 'رواه مسلم' },
        { id: 108, category: 'sabah', text: 'اللهم فاطر السموات والأرض، عالم الغيب والشهادة، ربَّ كلِّ شيء ومليكه، أشهد أنْ لا إله إلا أنت، أعوذ بك من شرِّ نفسي، وشر الشيطان وشِرْكه، وأن أَقترف على نفسي سوءًا، أو أجرَّه إلى مسلم.', count: 1, reference: 'صحيح؛ رواه الترمذي' },
        { id: 109, category: 'sabah', text: 'رضيت بالله ربًّا، وبالإسلام دينًا، وبمحمد -صلى الله عليه وسلم- نبيًّا.', count: 1, reference: 'حسن؛ رواه الترمذي' },
        { id: 110, category: 'sabah', text: 'يا حي يا قيُّوم، برحمتك أستغيث، أصلِح لي شأني كله، ولا تَكلني إلى نفسي طرْفة عينٍ.', count: 1, reference: 'حسن؛ رواه الحاكم' },
        { id: 111, category: 'sabah', text: 'لا إله إلا الله وحده لا شريك له، له الملك وله الحمد، وهو على كل شيء قدير.', count: 100, reference: 'رواه البخاري، ومسلم' },
        { id: 112, category: 'sabah', text: 'سبحان الله وبحمده عدد خلقه، ورضا نفسه، وزِنة عرشه، ومداد كلماته.', count: 3, reference: 'رواه مسلم' },
        { id: 113, category: 'sabah', text: '﴿ اللَّهُ لَا إِلَهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ... ﴾', count: 1, reference: 'آية الكرسي' },
        { id: 114, category: 'sabah', text: 'سورة الإخلاص.', count: 3, reference: 'صحيح؛ رواه أبو داود' },
        { id: 115, category: 'sabah', text: 'سورة الفلق.', count: 3, reference: 'صحيح؛ رواه أبو داود' },
        { id: 116, category: 'sabah', text: 'سورة الناس.', count: 3, reference: 'صحيح؛ رواه أبو داود' },
        { id: 117, category: 'sabah', text: 'بسم الله الذي لا يضرُّ مع اسمه شيء في الأرض ولا في السماء وهو السميع العليم.', count: 3, reference: 'صحيح؛ رواه الترمذي' },
        { id: 118, category: 'sabah', text: 'اللهم إني أصبحتُ أُشهدك وأُشهد حمَلة عرشك وملائكتك، وجميع خلْقك أنَّك أنت الله، لا إله إلا أنت وأن محمدًا عبدك ورسولك.', count: 4, reference: 'حسن؛ رواه أبو داود' },
        { id: 119, category: 'sabah', text: 'اللهم إني أسألك علمًا نافعًا ورزقًا طيبًا وعملاً متقبَّلاً.', count: 1, reference: 'صحيح؛ رواه ابن ماجه' },
        { id: 120, category: 'sabah', text: 'سبحان الله وبحمده.', count: 100, reference: 'رواه مسلم' },
        { id: 121, category: 'sabah', text: 'أستغفر الله.', count: 100, reference: 'صحيح؛ رواه الطبراني' },
        { id: 122, category: 'sabah', text: 'سبحان الله', count: 100, description: 'قبل طلوع الشمس' },
        { id: 123, category: 'sabah', text: 'الحمد لله', count: 100, description: 'قبل طلوع الشمس' },
        { id: 124, category: 'sabah', text: 'الله أكبر', count: 100, description: 'قبل طلوع الشمس' },
        { id: 125, category: 'sabah', text: 'لا إله إلا الله وحده لا شريك له ، له الملك وله الحمد وهو على كل شيء قديرٌ', count: 100, description: 'قبل طلوع الشمس' },
    ],
    'masaa': [
        { id: 201, category: 'masaa', text: 'اللهم أنت ربي، لا إله إلا أنت، خلَقتني وأنا عبدك، وأنا على عهدك ووعدك ما استطعت، أعوذ بك من شرِّ ما صنعت، أبُوء لك بنعمتك عليّ وأبوء بذنبي، فاغفر لي؛ فإنه لا يغفر الذنوب إلا أنت.', count: 1, reference: 'رواه البخاري' },
        { id: 202, category: 'masaa', text: 'اللهم بك أمسينا، وبك أصبَحنا، وبك نحيا، وبك نموت، وإليك المصير.', count: 1, reference: 'صحيح؛ رواه الترمذي' },
        { id: 203, category: 'masaa', text: 'أمسينا على فِطرة الإسلام، وكلمة الإخلاص، ودين نبينا محمد -صلى الله عليه وسلم- ومِلة أبينا إبراهيم حنيفًا مسلمًا وما كان من المشركين.', count: 1, reference: 'صحيح؛ رواه أحمد' },
        { id: 204, category: 'masaa', text: 'اللهم إني أسألك العافية في الدنيا والآخرة، اللهم إني أسألك العفو والعافية في ديني ودنياي، وأهلي ومالي، اللهم استُر عوراتي، وآمِن رَوعاتي، اللهم احفظني من بين يدي ومن خلفي، وعن يميني وعن شمالي، ومن فوقي، وأعوذ بعظمتك أن أُغتال من تحتي.', count: 1, reference: 'صحيح؛ رواه أبو داود' },
        { id: 205, category: 'masaa', text: 'اللهم عافني في بدني، اللهم عافني في سمعي، اللهم عافني في بصري، لا إله إلا أنت.', count: 3, reference: 'حسن؛ رواه أحمد' },
        { id: 206, category: 'masaa', text: 'اللهم إني أعوذ بك من الكفر والفقر، اللهم إني أعوذ بك من عذاب القبر، لا إله إلا أنت.', count: 3, reference: 'حسن؛ رواه أحمد' },
        { id: 207, category: 'masaa', text: 'أمسينا وأمسى المُلك لله، والحمد لله، لا إله إلا الله وحده لا شريك له، له الملك وله الحمد وهو على كل شيء قدير، ربِّ أسألك خير ما في هذه الليلة، وخير ما بعدها، وأعوذ بك من شرِّ ما في هذه الليلة، وشر ما بعدها، ربِّ أعوذ بك من الكسل، وسوء الكِبَر، ربِّ أعوذ بك من عذابٍ في النار وعذاب في القبر.', count: 1, reference: 'رواه مسلم' },
        { id: 208, category: 'masaa', text: 'اللهم فاطر السموات والأرض، عالم الغيب والشهادة، ربَّ كلِّ شيء ومليكه، أشهد أنْ لا إله إلا أنت، أعوذ بك من شرِّ نفسي، وشر الشيطان وشِرْكه، وأن أَقترف على نفسي سوءًا، أو أجرَّه إلى مسلم.', count: 1, reference: 'صحيح؛ رواه الترمذي' },
        { id: 209, category: 'masaa', text: 'رضيت بالله ربًّا، وبالإسلام دينًا، وبمحمد -صلى الله عليه وسلم- نبيًّا.', count: 1, reference: 'حسن؛ رواه الترمذي' },
        { id: 210, category: 'masaa', text: '﴿ اللَّهُ لَا إِلَهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ... ﴾', count: 1, reference: 'آية الكرسي' },
        { id: 211, category: 'masaa', text: 'سورة الإخلاص.', count: 3, reference: 'صحيح؛ رواه أبو داود' },
        { id: 212, category: 'masaa', text: 'سورة الفلق.', count: 3, reference: 'صحيح؛ رواه أبو داود' },
        { id: 213, category: 'masaa', text: 'سورة الناس.', count: 3, reference: 'صحيح؛ رواه أبو داود' },
        { id: 214, category: 'masaa', text: 'بسم الله الذي لا يضرُّ مع اسمه شيء في الأرض ولا في السماء وهو السميع العليم.', count: 3, reference: 'صحيح؛ رواه الترمذي' },
        { id: 215, category: 'masaa', text: 'اللهم إني أمسيتُ أُشهدك وأُشهد حمَلة عرشك وملائكتك، وجميع خلْقك أنَّك أنت الله، لا إله إلا أنت وأن محمدًا عبدك ورسولك.', count: 4, reference: 'حسن؛ رواه أبو داود' },
        { id: 216, category: 'masaa', text: 'سبحان الله وبحمده.', count: 100, reference: 'رواه مسلم' },
        { id: 217, category: 'masaa', text: 'سبحان الله', count: 100, description: 'قبل غروب الشمس' },
        { id: 218, category: 'masaa', text: 'الحمد لله', count: 100, description: 'قبل غروب الشمس' },
        { id: 219, category: 'masaa', text: 'الله أكبر', count: 100, description: 'قبل غروب الشمس' },
        { id: 220, category: 'masaa', text: 'لا إله إلا الله وحده لا شريك له ، له الملك وله الحمد وهو على كل شيء قديرٌ', count: 100, description: 'قبل غروب الشمس' },
    ],
    'postPrayer': [
        { id: 301, category: 'postPrayer', text: 'أستغفر الله، أستغفر الله، أستغفر الله', count: 1, reference: 'رواه مسلم' },
        { id: 302, category: 'postPrayer', text: 'اللهم أنت السلام، ومنك السلام، تبارَكت يا ذا الجلال والإكرام', count: 1, reference: 'رواه مسلم' },
        { id: 303, category: 'postPrayer', text: 'لا إله إلا الله، وحده لا شريك له، له الملك، وله الحمد وهو على كل شيء قدير، لا حول ولا قوة إلا بالله، لا إله إلا الله، ولا نعبد إلا إيَّاه، له النعمة وله الفضل، وله الثناء الحسن، لا إله إلا الله مخلصين له الدين ولو كرِه الكافرون', count: 1, reference: 'رواه مسلم' },
        { id: 304, category: 'postPrayer', text: 'لا إله إلا الله، وحده لا شريك له، له الملك وله الحمد وهو على كل شيء قدير، اللهم لا مانع لما أَعطيت، ولا معطي لما منعت، ولا ينفع ذا الجد منك الجد', count: 1, reference: 'البخاري ومسلم' },
        { id: 305, category: 'postPrayer', text: 'سبحان الله', count: 33, reference: 'رواه مسلم' },
        { id: 306, category: 'postPrayer', text: 'الحمد لله', count: 33, reference: 'رواه مسلم' },
        { id: 307, category: 'postPrayer', text: 'الله أكبر', count: 33, reference: 'رواه مسلم' },
        { id: 308, category: 'postPrayer', text: 'لا إله إلا الله وحده لا شريك له، له الملك وله الحمد وهو على كل شيء قدير', count: 1, description: 'تمام المائة' },
        { id: 309, category: 'postPrayer', text: 'قراءة سورة الإخلاص', count: 1 },
        { id: 310, category: 'postPrayer', text: 'قراءة سورة الفلق', count: 1 },
        { id: 311, category: 'postPrayer', text: 'قراءة سورة الناس', count: 1 },
    ],
    'sleep': [
        { id: 401, category: 'sleep', text: 'بِاسْمِكَ رَبِّـي وَضَعْـتُ جَنْـبي، وَبِكَ أَرْفَعُـه، فَإِن أَمْسَـكْتَ نَفْسـي فارْحَـمْها ، وَإِنْ أَرْسَلْتَـها فاحْفَظْـها بِمـا تَحْفَـظُ بِه عِبـادَكَ الصّـالِحـين.', count: 1 },
        { id: 402, category: 'sleep', text: 'اللّهُـمَّ قِنـي عَذابَـكَ يَـوْمَ تَبْـعَثُ عِبـادَك.', count: 3 },
        { id: 403, category: 'sleep', text: 'بِاسْـمِكَ اللّهُـمَّ أَمـوتُ وَأَحـيا.', count: 1 },
    ],
    'waking': [
        { id: 501, category: 'waking', text: 'الحمد لله الذي أحيانًا بعد ما أماتنا وإليه النشور.', count: 1, reference: 'رواه البخاري' },
        { id: 502, category: 'waking', text: 'الحمد لله الذي ردَّ علي رُوحي، وعافاني في جسدي، وأَذِن لي بذِكره.', count: 1, reference: 'حسن؛ رواه الترمذي' },
    ],
    'wudhu': [
        { id: 601, category: 'wudhu', text: 'بسم الله.', count: 1, description: 'قبل الوضوء', reference: 'حسن؛ رواه أبو داود' },
        { id: 602, category: 'wudhu', text: 'أشهد أنْ لا إله إلا الله وحده لا شريك له، وأشهد أن محمدًا عبده ورسوله.', count: 1, description: 'بعد الوضوء', reference: 'رواه مسلم' },
        { id: 603, category: 'wudhu', text: 'سبحانك اللهم وبحمْدك، أشهد أنْ لا إله إلا أنت، أستغفرك اللهم وأتوب إليك.', count: 1, description: 'بعد الوضوء', reference: 'حسن؛ رواه النسائي' },
    ],
    'mosque': [
        { id: 701, category: 'mosque', text: 'أعوذ بالله العظيم، وبوجهه الكريم، وسلطانه القديم - من الشيطان الرجيم.', count: 1, description: 'عند دخول المسجد' },
        { id: 702, category: 'mosque', text: 'بسم الله، والصلاة والسلام على رسول الله.', count: 1, description: 'عند دخول المسجد' },
        { id: 703, category: 'mosque', text: 'اللهم افتح لي أبواب رحمتك.', count: 1, description: 'عند دخول المسجد', reference: 'رواه مسلم' },
        { id: 704, category: 'mosque', text: 'اللهم إني أسألك من فضلك.', count: 1, description: 'عند الخروج من المسجد', reference: 'رواه مسلم' },
    ],
    'food': [
        { id: 801, category: 'food', text: 'بسم الله، فإن نسِي في أوله، فليقل: بسم الله في أوله وآخره.', count: 1, description: 'قبل الأكل', reference: 'صحيح؛ رواه الترمذي' },
        { id: 802, category: 'food', text: 'اللهم بارِك لنا فيه، وأطعمنا خيرًا منه.', count: 1, description: 'لمن أطعمه الله الطعام' },
        { id: 803, category: 'food', text: 'الحمد لله الذي أطعمني هذا، ورَزقنيه من غير حول مني ولا قوَّة.', count: 1, description: 'بعد الأكل', reference: 'صحيح؛ رواه أبو داود' },
        { id: 804, category: 'food', text: 'الحمد لله حمدًا كثيرًا طيبًا مباركًا فيه، غير مَكْفِيٍّ ولا مُودَّع، ولا مُستغنًى عنه ربَّنا.', count: 1, description: 'بعد الأكل', reference: 'رواه البخاري' },
    ],
    'home': [
        { id: 901, category: 'home', text: 'بسم الله وَلَجنا، وبسم الله خرجنا، وعلى الله ربنا توكَّلنا، ثم ليسلِّم على أهله.', count: 1, description: 'عند دخول المنزل', reference: 'حسن؛ رواه أبو داود' },
        { id: 902, category: 'home', text: 'بسم الله، توكَّلت على الله، ولا حول ولا قوة إلا بالله.', count: 1, description: 'عند الخروج من المنزل', reference: 'صحيح؛ رواه أبو داود' },
        { id: 903, category: 'home', text: 'اللهم إني أعوذ بك أن أَضِلَّ، أو أُضَل، أو أَزِل، أو أُزَل، أو أَظْلِم، أو أُظْلَم، أو أجْهَل، أو يُجهل علي.', count: 1, description: 'عند الخروج من المنزل', reference: 'صحيح؛ رواه ابن ماجه' },
    ],
    'travel': [
        { id: 1001, category: 'travel', text: 'بسم الله، الحمد لله: ﴿ سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ * وَإِنَّا إِلَى رَبِّنَا لَمُنْقَلِبُونَ ﴾. الحمد لله، الحمد لله، الحمد لله، الله أكبر، الله أكبر، الله أكبر، سبحانك اللهم إني ظلَمت نفسي فاغفر لي؛ فإنه لا يغفر الذنوب إلا أنت.', count: 1, description: 'دعاء ركوب الدابة', reference: 'صحيح؛ رواه أبو داود' },
        { id: 1002, category: 'travel', text: 'الله أكبر، الله أكبر، الله أكبر،﴿ سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ * وَإِنَّا إِلَى رَبِّنَا لَمُنْقَلِبُونَ ﴾. اللهمَّ إنَّا نسألك في سفرنا هذا البر والتقوى، ومن العمل ما ترضى، اللهم هوِّن علينا سفرنا هذا، واطْوِ عنَّا بُعده، اللهم أنت الصاحب في السفر، والخليفة في الأهل، اللهم إني أعوذ بك من وعثاء السفر، وكآبة المنظر، وسوء المُنقلَب في المال والأهل.', count: 1, description: 'دعاء السفر', reference: 'رواه مسلم' },
    ],
    'toilet': [
        { id: 1101, category: 'toilet', text: 'بسم الله', count: 1, description: 'قبل دخول الخلاء' },
        { id: 1102, category: 'toilet', text: 'اللهم إني أعوذ بك من الخُبث والخبائث.', count: 1, description: 'قبل دخول الخلاء', reference: 'رواه البخاري' },
        { id: 1103, category: 'toilet', text: 'غفرانك.', count: 1, description: 'بعد الخروج من الخلاء', reference: 'صحيح؛ رواه الترمذي' },
    ],
    'other': [
        { id: 1201, category: 'other', text: 'ربِّ اغفر لي، وتُب علي؛ إنك أنت التواب الرحيم.', count: 100, description: 'في المجلس الواحد', reference: 'صحيح؛ رواه أبو داود' },
        { id: 1202, category: 'other', text: 'سبحانك اللهم وبحمدك، أشهد أنْ لا إله إلا أنت، أستغفرك وأتوب إليك.', count: 1, description: 'كفارة المجلس', reference: 'صحيح؛ رواه أبو داود' },
        { id: 1203, category: 'other', text: 'اللهم إني عبدك، ابن عبدك، ابن أَمَتك، ناصيتي بيدك، ماضٍ فيّ حُكمك، عدْلٌ فيّ قضاؤك، أسألك بكل اسم هو لك، سمَّيت به نفسك، أو أنزَلته في كتابك، أو علَّمته أحدًا من خلقك، أو استأثَرت به في علم الغيب عندك، أن تجعل القرآن ربيع قلبي، ونور صدري، وجلاء حزني، وذَهاب همِّي.', count: 1, description: 'دعاء الهم والحزن' },
        { id: 1204, category: 'other', text: 'اللهم إني أعوذ بك من الهم والحزن، والعجز والكسل، والبخل والجُبن، وضَلَع الدَّين وغلَبة الرجال.', count: 1, description: 'دعاء الهم والحزن', reference: 'رواه البخاري' },
        { id: 1205, category: 'other', text: 'لا إله إلا الله العظيم الحليم، لا إله إلا الله رب العرش العظيم، لا إله إلا الله رب السماوات ورب الأرض ورب العرش الكريم.', count: 1, description: 'دعاء الكرب', reference: 'رواه البخاري، ومسلم' },
    ],
};